// icons.ts
export interface IconItem {
  id: string;
  name: string;
  category?: string[];
}

export const availableIcons: IconItem[] = [
  { id: 'ableton', name: 'Ableton', category: ['Software'] },
  { id: 'activitypub', name: 'ActivityPub', category: ['Social Media', 'Decentralized'] },
  { id: 'actix', name: 'Actix', category: ['Web Development', 'Rust Framework'] },
  { id: 'adonis', name: 'Adonis', category: ['Web Development', 'JavaScript Framework'] },
  { id: 'ae', name: 'After Effects', category: ['Design', 'Video Editing', 'Animation'] },
  { id: 'aiscript', name: 'Aiscript', category: ['Scripting', 'AI'] },
  { id: 'alpinejs', name: 'Alpine.js', category: ['Web Development', 'JavaScript Framework'] },
  { id: 'anaconda', name: 'Anaconda', category: ['Data Science', 'Python', 'Machine Learning'] },
  { id: 'androidstudio', name: 'Android Studio', category: ['Mobile Development'] },
  { id: 'angular', name: 'Angular', category: ['Web Development', 'JavaScript Framework'] },
  { id: 'ansible', name: 'Ansible', category: ['DevOps', 'Automation'] },
  { id: 'apollo', name: 'Apollo', category: ['Web Development', 'API'] },
  { id: 'apple', name: 'Apple', category: ['Mobile Development'] },
  { id: 'appwrite', name: 'Appwrite', category: ['Web Development'] },
  { id: 'arch', name: 'Arch', category: ['Linux', 'Operating System'] },
  { id: 'arduino', name: 'Arduino', category: ['IoT', 'Programming'] },
  { id: 'astro', name: 'Astro', category: ['Web Development', 'JavaScript Framework'] },
  { id: 'atom', name: 'Atom', category: ['Code Editor', 'Web Development'] },
  { id: 'au', name: 'Au', category: ['Design'] },
  { id: 'autocad', name: 'AutoCAD', category: ['Design'] },
  { id: 'aws', name: 'AWS', category: ['Cloud Computing', 'DevOps'] },
  { id: 'azul', name: 'Azul', category: ['Java', 'Software'] },
  { id: 'azure', name: 'Azure', category: ['Cloud Computing', 'DevOps'] },
  { id: 'babel', name: 'Babel', category: ['Web Development', 'JavaScript Tools'] },
  { id: 'bash', name: 'Bash', category: ['Scripting', 'Linux'] },
  { id: 'bevy', name: 'Bevy', category: ['Game Development'] },
  { id: 'bitbucket', name: 'Bitbucket', category: ['Version Control', 'DevOps'] },
  { id: 'blender', name: 'Blender', category: ['Design', '3D Modeling', 'Animation'] },
  { id: 'bootstrap', name: 'Bootstrap', category: ['Web Development', 'CSS Framework'] },
  { id: 'bsd', name: 'BSD', category: ['Operating System', 'Security'] },
  { id: 'bun', name: 'Bun', category: ['Web Development', 'JavaScript Runtime', 'Package Manager'] },
  { id: 'c', name: 'C', category: ['Programming Languages', 'Systems Programming'] },
  { id: 'cs', name: 'C#', category: ['Programming Languages', 'Game Development', 'Web Development'] },
  { id: 'cpp', name: 'C++', category: ['Programming Languages', 'Systems Programming', 'Game Development'] },
  { id: 'crystal', name: 'Crystal', category: ['Programming Languages', 'Web Development'] },
  { id: 'cassandra', name: 'Cassandra', category: ['Database'] },
  { id: 'clion', name: 'CLion', category: ['IDE', 'Programming Languages'] },
  { id: 'clojure', name: 'Clojure', category: ['Programming Languages', 'Functional Programming'] },
  { id: 'cloudflare', name: 'Cloudflare', category: ['Web Development', 'Security'] },
  { id: 'cmake', name: 'CMake', category: ['Build Tools', 'Programming'] },
  { id: 'codepen', name: 'CodePen', category: ['Web Development'] },
  { id: 'coffeescript', name: 'CoffeeScript', category: ['Web Development'] },
  { id: 'css', name: 'CSS', category: ['Web Development'] },
  { id: 'cypress', name: 'Cypress', category: ['Web Development', 'Testing'] },
  { id: 'd3', name: 'D3.js', category: ['Web Development', 'JavaScript Library'] },
  { id: 'dart', name: 'Dart', category: ['Programming Languages', 'Mobile Development', 'Web Development'] },
  { id: 'debian', name: 'Debian', category: ['Linux', 'Operating System'] },
  { id: 'deno', name: 'Deno', category: ['Web Development', 'JavaScript Runtime'] },
  { id: 'devto', name: 'Dev.to', category: ['Web Development', 'Community'] },
  { id: 'discord', name: 'Discord', category: ['Social Media', 'Community'] },
  { id: 'bots', name: 'Bots', category: ['Automation', 'AI'] },
  { id: 'discordjs', name: 'Discord.js', category: ['Web Development'] },
  { id: 'django', name: 'Django', category: ['Web Development', 'Python Framework'] },
  { id: 'docker', name: 'Docker', category: ['DevOps', 'Containerization', 'Cloud Computing'] },
  { id: 'dotnet', name: '.NET', category: ['Web Development'] },
  { id: 'dynamodb', name: 'DynamoDB', category: ['Database', 'Cloud Computing'] },
  { id: 'eclipse', name: 'Eclipse', category: ['IDE', 'Programming Languages'] },
  { id: 'elasticsearch', name: 'Elasticsearch', category: ['Database'] },
  { id: 'electron', name: 'Electron', category: ['Web Development'] },
  { id: 'elixir', name: 'Elixir', category: ['Programming Languages', 'Web Development'] },
  { id: 'elysia', name: 'Elysia', category: ['Web Development', 'JavaScript Tools'] },
  { id: 'emacs', name: 'Emacs', category: ['Text Editor', 'Scripting'] },
  { id: 'ember', name: 'Ember.js', category: ['Web Development', 'JavaScript Framework'] },
  { id: 'emotion', name: 'Emotion', category: ['Web Development'] },
  { id: 'express', name: 'Express', category: ['Web Development', 'JavaScript Framework'] },
  { id: 'fastapi', name: 'FastAPI', category: ['Web Development', 'Python Framework'] },
  { id: 'fediverse', name: 'Fediverse', category: ['Social Media', 'Decentralized'] },
  { id: 'figma', name: 'Figma', category: ['Design', 'UI/UX'] },
  { id: 'firebase', name: 'Firebase', category: ['Web Development', 'Cloud Computing'] },
  { id: 'flask', name: 'Flask', category: ['Web Development', 'Python Framework'] },
  { id: 'flutter', name: 'Flutter', category: ['Mobile Development', 'Web Development'] },
  { id: 'forth', name: 'Forth', category: ['Programming Languages'] },
  { id: 'fortran', name: 'Fortran', category: ['Programming Languages'] },
  { id: 'gamemakerstudio', name: 'GameMaker Studio', category: ['Game Development', 'Design'] },
  { id: 'gatsby', name: 'Gatsby', category: ['Web Development', 'JavaScript Framework'] },
  { id: 'gcp', name: 'GCP', category: ['Cloud Computing', 'DevOps'] },
  { id: 'git', name: 'Git', category: ['Version Control', 'DevOps'] },
  { id: 'github', name: 'GitHub', category: ['Version Control', 'DevOps'] },
  { id: 'gitlab', name: 'GitLab', category: ['Version Control', 'DevOps'] },
  { id: 'githubactions', name: 'GitHub Actions', category: ['Version Control', 'DevOps'] },
  { id: 'gmail', name: 'Gmail', category: [] },
  { id: 'gherkin', name: 'Gherkin', category: ['Testing'] },
  { id: 'go', name: 'Go', category: ['Programming Languages', 'Systems Programming'] },
  { id: 'gradle', name: 'Gradle', category: ['Build Tools', 'Java'] },
  { id: 'godot', name: 'Godot', category: ['Game Development', 'Design'] },
  { id: 'grafana', name: 'Grafana', category: ['Monitoring', 'DevOps'] },
  { id: 'graphql', name: 'GraphQL', category: ['Web Development', 'API'] },
  { id: 'gtk', name: 'GTK', category: ['Design', 'UI/UX'] },
  { id: 'gulp', name: 'Gulp', category: ['Web Development'] },
  { id: 'haskell', name: 'Haskell', category: ['Programming Languages', 'Functional Programming'] },
  { id: 'haxe', name: 'Haxe', category: ['Programming Languages', 'Game Development'] },
  { id: 'haxeflixel', name: 'HaxeFlixel', category: ['Game Development', 'Design'] },
  { id: 'heroku', name: 'Heroku', category: ['Cloud Computing', 'Web Development'] },
  { id: 'hibernate', name: 'Hibernate', category: ['Web Development', 'Java Framework'] },
  { id: 'html', name: 'HTML', category: ['Web Development'] },
  { id: 'htmx', name: 'HTMX', category: ['Web Development', 'JavaScript Tools'] },
  { id: 'idea', name: 'IntelliJ IDEA', category: ['IDE', 'Programming Languages'] },
  { id: 'ai', name: 'Illustrator', category: ['Design'] },
  { id: 'instagram', name: 'Instagram', category: ['Social Media', 'Community'] },
  { id: 'ipfs', name: 'IPFS', category: ['Web Development', 'Decentralized'] },
  { id: 'java', name: 'Java', category: ['Programming Languages', 'Web Development'] },
  { id: 'javascript', name: 'JavaScript', category: ['Programming Languages', 'Web Development'] },
  { id: 'jenkins', name: 'Jenkins', category: ['DevOps', 'Automation'] },
  { id: 'jest', name: 'Jest', category: ['Web Development', 'Testing'] },
  { id: 'jquery', name: 'jQuery', category: ['Web Development', 'JavaScript Library'] },
  { id: 'julia', name: 'Julia', category: ['Programming Languages', 'Data Science', 'Machine Learning'] },
  { id: 'kafka', name: 'Kafka', category: ['Web Development'] },
  { id: 'kali', name: 'Kali Linux', category: ['Security', 'Operating System'] },
  { id: 'kotlin', name: 'Kotlin', category: ['Programming Languages', 'Mobile Development', 'Web Development'] },
  { id: 'ktor', name: 'Ktor', category: ['Web Development'] },
  { id: 'kubernetes', name: 'Kubernetes', category: ['DevOps', 'Containerization'] },
  { id: 'laravel', name: 'Laravel', category: ['Web Development', 'PHP Framework'] },
  { id: 'latex', name: 'LaTeX', category: [] },
  { id: 'less', name: 'Less', category: ['Web Development', 'CSS Preprocessor'] },
  { id: 'linkedin', name: 'LinkedIn', category: ['Social Media', 'Community'] },
  { id: 'linux', name: 'Linux', category: ['Operating System'] },
  { id: 'lit', name: 'Lit', category: ['Web Development', 'JavaScript Framework'] },
  { id: 'lua', name: 'Lua', category: ['Programming Languages', 'Game Development'] },
  { id: 'md', name: 'Markdown', category: ['Web Development', 'Documentation'] },
  { id: 'mastodon', name: 'Mastodon', category: ['Social Media', 'Decentralized'] },
  { id: 'materialui', name: 'Material-UI', category: ['Web Development'] },
  { id: 'matlab', name: 'MATLAB', category: ['Programming Languages', 'Data Science'] },
  { id: 'maven', name: 'Maven', category: ['Build Tools', 'Java'] },
  { id: 'mint', name: 'Mint', category: ['Web Development', 'Programming Languages'] },
  { id: 'misskey', name: 'Misskey', category: ['Social Media', 'Decentralized'] },
  { id: 'mongodb', name: 'MongoDB', category: ['Database'] },
  { id: 'mysql', name: 'MySQL', category: ['Database', 'Web Development'] },
  { id: 'neovim', name: 'Neovim', category: ['Text Editor', 'Programming'] },
  { id: 'nestjs', name: 'Nest.js', category: ['Web Development'] },
  { id: 'netlify', name: 'Netlify', category: ['Web Development', 'Hosting'] },
  { id: 'nextjs', name: 'Next.js', category: ['Web Development', 'JavaScript Framework'] },
  { id: 'nginx', name: 'Nginx', category: ['Web Development'] },
  { id: 'nim', name: 'Nim', category: ['Programming Languages', 'Systems Programming'] },
  { id: 'nix', name: 'Nix', category: ['Package Manager', 'Linux'] },
  { id: 'nodejs', name: 'Node.js', category: ['Web Development', 'JavaScript Runtime'] },
  { id: 'notion', name: 'Notion', category: ['Productivity', 'Documentation'] },
  { id: 'npm', name: 'NPM', category: ['Web Development', 'Package Manager'] },
  { id: 'nuxtjs', name: 'Nuxt.js', category: ['Web Development', 'JavaScript Framework'] },
  { id: 'obsidian', name: 'Obsidian', category: ['Productivity'] },
  { id: 'ocaml', name: 'OCaml', category: ['Programming Languages', 'Functional Programming'] },
  { id: 'octave', name: 'Octave', category: ['Programming Languages', 'Data Science'] },
  { id: 'opencv', name: 'OpenCV', category: ['AI'] },
  { id: 'openshift', name: 'OpenShift', category: ['DevOps', 'Containerization'] },
  { id: 'openstack', name: 'OpenStack', category: ['Cloud Computing', 'DevOps'] },
  { id: 'p5js', name: 'p5.js', category: ['Web Development', 'JavaScript Library'] },
  { id: 'perl', name: 'Perl', category: ['Programming Languages', 'Scripting'] },
  { id: 'ps', name: 'Photoshop', category: ['Design'] },
  { id: 'php', name: 'PHP', category: ['Programming Languages', 'Web Development'] },
  { id: 'phpstorm', name: 'PHPStorm', category: ['IDE', 'PHP Framework'] },
  { id: 'pinia', name: 'Pinia', category: ['Web Development', 'Vue.js'] },
  { id: 'pkl', name: 'Pickle', category: ['Data Science', 'Python'] },
  { id: 'plan9', name: 'Plan 9', category: ['Operating System', 'Linux'] },
  { id: 'planetscale', name: 'PlanetScale', category: ['Database', 'Cloud Computing'] },
  { id: 'pnpm', name: 'PNPM', category: ['Web Development', 'Package Manager'] },
  { id: 'postgresql', name: 'PostgreSQL', category: ['Database', 'Web Development'] },
  { id: 'postman', name: 'Postman', category: ['Web Development', 'API'] },
  { id: 'powershell', name: 'PowerShell', category: ['Scripting'] },
  { id: 'pr', name: 'Premiere Pro', category: ['Design', 'Video Editing'] },
  { id: 'prisma', name: 'Prisma', category: ['Web Development', 'Database'] },
  { id: 'processing', name: 'Processing', category: ['Design', 'Programming Languages'] },
  { id: 'prometheus', name: 'Prometheus', category: ['Monitoring', 'DevOps'] },
  { id: 'pug', name: 'Pug', category: ['Web Development'] },
  { id: 'pycharm', name: 'PyCharm', category: ['IDE', 'Python'] },
  { id: 'py', name: 'Python', category: ['Programming Languages', 'Data Science', 'Web Development', 'AI'] },
  { id: 'pytorch', name: 'PyTorch', category: ['Machine Learning', 'AI'] },
  { id: 'qt', name: 'Qt', category: ['Design'] },
  { id: 'r', name: 'R', category: ['Data Science', 'Programming Languages'] },
  { id: 'rabbitmq', name: 'RabbitMQ', category: ['Web Development'] },
  { id: 'rails', name: 'Rails', category: ['Web Development'] },
  { id: 'raspberrypi', name: 'Raspberry Pi', category: ['IoT'] },
  { id: 'react', name: 'React', category: ['Web Development', 'JavaScript Framework'] },
  { id: 'reactivex', name: 'ReactiveX', category: ['Web Development', 'JavaScript Library'] },
  { id: 'redhat', name: 'Red Hat', category: ['Linux', 'Operating System'] },
  { id: 'redis', name: 'Redis', category: ['Database'] },
  { id: 'redux', name: 'Redux', category: ['Web Development'] },
  { id: 'regex', name: 'Regex', category: ['Web Development', 'Programming'] },
  { id: 'remix', name: 'Remix', category: ['Web Development', 'JavaScript Framework'] },
  { id: 'replit', name: 'Replit', category: ['Web Development', 'IDE'] },
  { id: 'rider', name: 'Rider', category: ['IDE', 'Programming Languages'] },
  { id: 'robloxstudio', name: 'Roblox Studio', category: ['Game Development', 'Design'] },
  { id: 'rocket', name: 'Rocket', category: ['Web Development', 'Rust Framework'] },
  { id: 'rollupjs', name: 'Rollup.js', category: ['Web Development', 'JavaScript Tools'] },
  { id: 'ros', name: 'ROS', category: ['Programming'] },
  { id: 'ruby', name: 'Ruby', category: ['Programming Languages', 'Web Development'] },
  { id: 'rust', name: 'Rust', category: ['Programming Languages', 'Systems Programming'] },
  { id: 'sass', name: 'Sass', category: ['Web Development', 'CSS Preprocessor'] },
  { id: 'spring', name: 'Spring', category: ['Web Development', 'Java Framework'] },
  { id: 'sqlite', name: 'SQLite', category: ['Database', 'Web Development'] },
  { id: 'stackoverflow', name: 'Stack Overflow', category: ['Community', 'Programming'] },
  { id: 'styledcomponents', name: 'Styled Components', category: ['Web Development'] },
  { id: 'sublime', name: 'Sublime Text', category: ['Text Editor', 'Programming'] },
  { id: 'supabase', name: 'Supabase', category: ['Web Development', 'Database'] },
  { id: 'scala', name: 'Scala', category: ['Programming Languages', 'Web Development'] },
  { id: 'sklearn', name: 'Scikit-learn', category: ['Data Science', 'Python'] },
  { id: 'selenium', name: 'Selenium', category: ['Web Development', 'Testing'] },
  { id: 'sentry', name: 'Sentry', category: ['Monitoring', 'DevOps'] },
  { id: 'sequelize', name: 'Sequelize', category: ['Web Development', 'Database'] },
  { id: 'sketchup', name: 'SketchUp', category: ['Design', '3D Modeling'] },
  { id: 'solidity', name: 'Solidity', category: ['Programming'] },
  { id: 'solidjs', name: 'Solid.js', category: ['Web Development', 'JavaScript Framework'] },
  { id: 'svelte', name: 'Svelte', category: ['Web Development', 'JavaScript Framework'] },
  { id: 'svg', name: 'SVG', category: ['Web Development'] },
  { id: 'swift', name: 'Swift', category: ['Programming Languages', 'Mobile Development'] },
  { id: 'symfony', name: 'Symfony', category: ['Web Development', 'PHP Framework'] },
  { id: 'tailwind', name: 'Tailwind CSS', category: ['Web Development', 'CSS Framework'] },
  { id: 'tauri', name: 'Tauri', category: ['Web Development', 'Rust Framework'] },
  { id: 'tensorflow', name: 'TensorFlow', category: ['Machine Learning', 'AI'] },
  { id: 'terraform', name: 'Terraform', category: ['DevOps'] },
  { id: 'threejs', name: 'Three.js', category: ['Web Development', 'JavaScript Library'] },
  { id: 'twitter', name: 'Twitter', category: ['Social Media', 'Community'] },
  { id: 'ts', name: 'TypeScript', category: ['Programming Languages', 'Web Development'] },
  { id: 'ubuntu', name: 'Ubuntu', category: ['Operating System', 'Linux'] },
  { id: 'unity', name: 'Unity', category: ['Game Development', 'Design'] },
  { id: 'unreal', name: 'Unreal Engine', category: ['Game Development', 'Design'] },
  { id: 'v', name: 'V', category: ['Programming Languages', 'Web Development'] },
  { id: 'vala', name: 'Vala', category: ['Programming Languages', 'Systems Programming'] },
  { id: 'vercel', name: 'Vercel', category: ['Web Development', 'Hosting'] },
  { id: 'vim', name: 'Vim', category: ['Text Editor', 'Scripting'] },
  { id: 'visualstudio', name: 'Visual Studio', category: ['IDE', 'Programming Languages'] },
  { id: 'vite', name: 'Vite', category: ['Web Development', 'JavaScript Tools'] },
  { id: 'vitest', name: 'Vitest', category: ['Web Development', 'Testing'] },
  { id: 'vscode', name: 'VS Code', category: ['Code Editor', 'Web Development'] },
  { id: 'vscodium', name: 'VSCodium', category: ['Code Editor', 'Web Development'] },
  { id: 'vue', name: 'Vue.js', category: ['Web Development', 'JavaScript Framework', 'Vue.js'] },
  { id: 'vuetify', name: 'Vuetify', category: ['Web Development', 'Vue.js'] },
  { id: 'wasm', name: 'WebAssembly', category: ['Programming Languages', 'Web Development'] },
  { id: 'webflow', name: 'Webflow', category: ['Web Development', 'Design'] },
  { id: 'webpack', name: 'Webpack', category: ['Web Development', 'JavaScript Tools'] },
  { id: 'webstorm', name: 'WebStorm', category: ['IDE', 'Web Development'] },
  { id: 'windicss', name: 'Windi CSS', category: ['Web Development', 'CSS Framework'] },
  { id: 'windows', name: 'Windows', category: ['Operating System'] },
  { id: 'wordpress', name: 'WordPress', category: ['Web Development'] },
  { id: 'workers', name: 'Workers', category: ['Web Development', 'Cloud Computing'] },
  { id: 'xd', name: 'Adobe XD', category: ['Design', 'UI/UX'] },
  { id: 'yarn', name: 'Yarn', category: ['Web Development', 'Package Manager'] },
  { id: 'yew', name: 'Yew', category: ['Web Development', 'Rust Framework'] },
  { id: 'zig', name: 'Zig', category: ['Programming Languages', 'Systems Programming'] },
];