// icons.ts (God Bless ChatGPT)
export interface IconItem {
  id: string;
  name: string;
  category?: string[];
}

export const availableIcons: IconItem[] = [
  { id: 'ableton', name: 'Ableton', category: ['Music Production', 'Software'] },
  { id: 'activitypub', name: 'ActivityPub', category: ['Social Media', 'Decentralization'] },
  { id: 'actix', name: 'Actix', category: ['Web Development', 'Rust Framework'] },
  { id: 'adonis', name: 'Adonis', category: ['Web Development', 'JavaScript Framework'] },
  { id: 'ae', name: 'After Effects', category: ['Design', 'Video Editing', 'Animation'] },
  { id: 'aiscript', name: 'Aiscript', category: ['Scripting', 'AI'] },
  { id: 'alpinejs', name: 'Alpine.js', category: ['Web Development', 'JavaScript Framework'] },
  { id: 'anaconda', name: 'Anaconda', category: ['Data Science', 'Python', 'Machine Learning'] },
  { id: 'androidstudio', name: 'Android Studio', category: ['Mobile Development', 'Android'] },
  { id: 'angular', name: 'Angular', category: ['Web Development', 'JavaScript Framework'] },
  { id: 'ansible', name: 'Ansible', category: ['DevOps', 'Automation', 'Configuration Management'] },
  { id: 'apollo', name: 'Apollo', category: ['Web Development', 'GraphQL'] },
  { id: 'apple', name: 'Apple', category: ['Tech', 'Mobile Development'] },
  { id: 'appwrite', name: 'Appwrite', category: ['Web Development', 'Backend'] },
  { id: 'arch', name: 'Arch', category: ['Linux', 'Operating System'] },
  { id: 'arduino', name: 'Arduino', category: ['IoT', 'Hardware', 'Programming'] },
  { id: 'astro', name: 'Astro', category: ['Web Development', 'JavaScript Framework'] },
  { id: 'atom', name: 'Atom', category: ['Code Editor', 'Web Development'] },
  { id: 'au', name: 'Au', category: ['Design', 'Audio'] },
  { id: 'autocad', name: 'AutoCAD', category: ['Design', 'Architecture', 'Engineering'] },
  { id: 'aws', name: 'AWS', category: ['Cloud Computing', 'DevOps'] },
  { id: 'azul', name: 'Azul', category: ['Java', 'Software'] },
  { id: 'azure', name: 'Azure', category: ['Cloud Computing', 'DevOps'] },
  { id: 'babel', name: 'Babel', category: ['Web Development', 'JavaScript'] },
  { id: 'bash', name: 'Bash', category: ['Scripting', 'Shell', 'Linux'] },
  { id: 'bevy', name: 'Bevy', category: ['Game Development', 'Rust'] },
  { id: 'bitbucket', name: 'Bitbucket', category: ['Version Control', 'DevOps'] },
  { id: 'blender', name: 'Blender', category: ['Design', '3D Modeling', 'Animation'] },
  { id: 'bootstrap', name: 'Bootstrap', category: ['Web Development', 'CSS Framework'] },
  { id: 'bsd', name: 'BSD', category: ['Operating System', 'Security'] },
  { id: 'bun', name: 'Bun', category: ['Web Development', 'JavaScript Runtime'] },
  { id: 'c', name: 'C', category: ['Programming Languages', 'Systems Programming'] },
  { id: 'cs', name: 'C#', category: ['Programming Languages', 'Game Development', 'Web Development'] },
  { id: 'cpp', name: 'C++', category: ['Programming Languages', 'Systems Programming', 'Game Development'] },
  { id: 'crystal', name: 'Crystal', category: ['Programming Languages', 'Web Development'] },
  { id: 'cassandra', name: 'Cassandra', category: ['Database', 'Big Data'] },
  { id: 'clion', name: 'CLion', category: ['IDE', 'Programming Languages'] },
  { id: 'clojure', name: 'Clojure', category: ['Programming Languages', 'Functional Programming'] },
  { id: 'cloudflare', name: 'Cloudflare', category: ['Web Development', 'Security'] },
  { id: 'cmake', name: 'CMake', category: ['Build Tools', 'Programming'] },
  { id: 'codepen', name: 'CodePen', category: ['Web Development', 'Frontend'] },
  { id: 'coffeescript', name: 'CoffeeScript', category: ['Web Development', 'JavaScript'] },
  { id: 'css', name: 'CSS', category: ['Web Development', 'Styling'] },
  { id: 'cypress', name: 'Cypress', category: ['Web Development', 'Testing'] },
  { id: 'd3', name: 'D3.js', category: ['Data Visualization', 'JavaScript'] },
  { id: 'dart', name: 'Dart', category: ['Programming Languages', 'Mobile Development', 'Web Development'] },
  { id: 'debian', name: 'Debian', category: ['Linux', 'Operating System'] },
  { id: 'deno', name: 'Deno', category: ['Web Development', 'JavaScript Runtime'] },
  { id: 'devto', name: 'Dev.to', category: ['Web Development', 'Community'] },
  { id: 'discord', name: 'Discord', category: ['Social Media', 'Community'] },
  { id: 'bots', name: 'Bots', category: ['Automation', 'AI'] },
  { id: 'discordjs', name: 'Discord.js', category: ['Web Development', 'Bot Development'] },
  { id: 'django', name: 'Django', category: ['Web Development', 'Python Framework'] },
  { id: 'docker', name: 'Docker', category: ['DevOps', 'Containerization', 'Cloud Computing'] },
  { id: 'dotnet', name: '.NET', category: ['Web Development', 'Programming Framework'] },
  { id: 'dynamodb', name: 'DynamoDB', category: ['Database', 'Cloud Computing'] },
  { id: 'eclipse', name: 'Eclipse', category: ['IDE', 'Programming Languages'] },
  { id: 'elasticsearch', name: 'Elasticsearch', category: ['Database', 'Search'] },
  { id: 'electron', name: 'Electron', category: ['Web Development', 'Desktop Apps'] },
  { id: 'elixir', name: 'Elixir', category: ['Programming Languages', 'Web Development'] },
  { id: 'elysia', name: 'Elysia', category: ['Web Development', 'JavaScript'] },
  { id: 'emacs', name: 'Emacs', category: ['Text Editor', 'Scripting'] },
  { id: 'ember', name: 'Ember.js', category: ['Web Development', 'JavaScript Framework'] },
  { id: 'emotion', name: 'Emotion', category: ['Web Development', 'CSS-in-JS'] },
  { id: 'express', name: 'Express', category: ['Web Development', 'JavaScript Framework'] },
  { id: 'fastapi', name: 'FastAPI', category: ['Web Development', 'Python Framework'] },
  { id: 'fediverse', name: 'Fediverse', category: ['Social Media', 'Decentralization'] },
  { id: 'figma', name: 'Figma', category: ['Design', 'UI/UX'] },
  { id: 'firebase', name: 'Firebase', category: ['Web Development', 'Cloud Computing'] },
  { id: 'flask', name: 'Flask', category: ['Web Development', 'Python Framework'] },
  { id: 'flutter', name: 'Flutter', category: ['Mobile Development', 'Web Development'] },
  { id: 'forth', name: 'Forth', category: ['Programming Languages', 'Embedded Systems'] },
  { id: 'fortran', name: 'Fortran', category: ['Programming Languages', 'High-Performance Computing'] },
  { id: 'gamemakerstudio', name: 'GameMaker Studio', category: ['Game Development', 'Design'] },
  { id: 'gatsby', name: 'Gatsby', category: ['Web Development', 'JavaScript Framework'] },
  { id: 'gcp', name: 'GCP', category: ['Cloud Computing', 'DevOps'] },
  { id: 'git', name: 'Git', category: ['Version Control', 'DevOps'] },
  { id: 'github', name: 'GitHub', category: ['Version Control', 'DevOps'] },
  { id: 'gitlab', name: 'GitLab', category: ['Version Control', 'DevOps'] },
  { id: 'godot', name: 'Godot', category: ['Game Development', 'Design'] },
  { id: 'go', name: 'Go', category: ['Programming Languages', 'Systems Programming'] },
  { id: 'grafana', name: 'Grafana', category: ['Monitoring', 'DevOps'] },
  { id: 'graphql', name: 'GraphQL', category: ['Web Development', 'API'] },
  { id: 'gulp', name: 'Gulp', category: ['Web Development', 'Task Runner'] },
  { id: 'haskell', name: 'Haskell', category: ['Programming Languages', 'Functional Programming'] },
  { id: 'haxe', name: 'Haxe', category: ['Programming Languages', 'Game Development'] },
  { id: 'heroku', name: 'Heroku', category: ['Cloud Computing', 'Web Development'] },
  { id: 'html', name: 'HTML', category: ['Web Development', 'Markup Language'] },
  { id: 'java', name: 'Java', category: ['Programming Languages', 'Web Development'] },
  { id: 'javascript', name: 'JavaScript', category: ['Programming Languages', 'Web Development'] },
  { id: 'jest', name: 'Jest', category: ['Web Development', 'Testing'] },
  { id: 'julia', name: 'Julia', category: ['Programming Languages', 'Data Science', 'Machine Learning'] },
  { id: 'kafka', name: 'Kafka', category: ['Data Streaming', 'Web Development'] },
  { id: 'kotlin', name: 'Kotlin', category: ['Programming Languages', 'Mobile Development', 'Web Development'] },
  { id: 'kubernetes', name: 'Kubernetes', category: ['DevOps', 'Cloud Computing'] },
  { id: 'laravel', name: 'Laravel', category: ['Web Development', 'PHP Framework'] },
  { id: 'less', name: 'Less', category: ['Web Development', 'CSS Preprocessor'] },
  { id: 'linux', name: 'Linux', category: ['Operating System', 'Security'] },
  { id: 'lua', name: 'Lua', category: ['Programming Languages', 'Game Development'] },
  { id: 'mongodb', name: 'MongoDB', category: ['Database', 'NoSQL'] },
  { id: 'mysql', name: 'MySQL', category: ['Database', 'Web Development'] },
  { id: 'nextjs', name: 'Next.js', category: ['Web Development', 'JavaScript Framework'] },
  { id: 'nginx', name: 'Nginx', category: ['Web Development', 'Web Server'] },
  { id: 'nodejs', name: 'Node.js', category: ['Web Development', 'JavaScript Runtime'] },
  { id: 'npm', name: 'NPM', category: ['Web Development', 'Package Manager'] },
  { id: 'nuxtjs', name: 'Nuxt.js', category: ['Web Development', 'JavaScript Framework'] },
  { id: 'opencv', name: 'OpenCV', category: ['Computer Vision', 'AI'] },
  { id: 'php', name: 'PHP', category: ['Programming Languages', 'Web Development'] },
  { id: 'postgresql', name: 'PostgreSQL', category: ['Database', 'Web Development'] },
  { id: 'python', name: 'Python', category: ['Programming Languages', 'Data Science', 'Web Development', 'AI'] },
  { id: 'react', name: 'React', category: ['Web Development', 'JavaScript Framework'] },
  { id: 'redis', name: 'Redis', category: ['Database', 'Cache'] },
  { id: 'redux', name: 'Redux', category: ['Web Development', 'State Management'] },
  { id: 'rust', name: 'Rust', category: ['Programming Languages', 'Systems Programming'] },
  { id: 'sass', name: 'Sass', category: ['Web Development', 'CSS Preprocessor'] },
  { id: 'scala', name: 'Scala', category: ['Programming Languages', 'Functional Programming'] },
  { id: 'scss', name: 'SCSS', category: ['Web Development', 'CSS Preprocessor'] },
  { id: 'spring', name: 'Spring', category: ['Web Development', 'Java Framework'] },
  { id: 'svelte', name: 'Svelte', category: ['Web Development', 'JavaScript Framework'] },
  { id: 'swift', name: 'Swift', category: ['Programming Languages', 'Mobile Development'] },
  { id: 'tailwindcss', name: 'Tailwind CSS', category: ['Web Development', 'CSS Framework'] },
  { id: 'tensorflow', name: 'TensorFlow', category: ['Machine Learning', 'AI'] },
  { id: 'typescript', name: 'TypeScript', category: ['Programming Languages', 'Web Development'] },
  { id: 'unity', name: 'Unity', category: ['Game Development', 'Design'] },
  { id: 'vue', name: 'Vue.js', category: ['Web Development', 'JavaScript Framework'] },
  { id: 'webpack', name: 'Webpack', category: ['Web Development', 'Build Tools'] },
  { id: 'wordpress', name: 'WordPress', category: ['Web Development', 'CMS'] }
];